### ISSUE TITLE
Erro 500 em Pagamento Recorrente

### ISSUE THREAD

**Issue by crfcarlos** [DeveloperCielo/API-3.0-PHP#137]
Senhores antes mesmo de recorrer a este suporte, já tentei de todas as formas com o suporte da Cielo e sem sucesso, já estou a seis meses nesta demanda e não consigo ter exito.

Peço ajuda, preciso concluir está requisição para a empresa.
 
Na minha máquina de desenvolvimento local, funciona corretamente.
No meu servidor Amazon - AWS, ocorre o erro 500.
Ambas são linux 18.04 lts com php 7.2, apacahe 2 e Composer.
Abaixo estou enviando o código efetuar-pagamento.php

![image](https://user-images.githubusercontent.com/19939398/52786832-17198000-3043-11e9-8089-d1c49ba24b68.png)

<?php

session_start();

require 'vendor/autoload.php';

use Cielo\API30\Merchant;

use Cielo\API30\Ecommerce\Environment;
use Cielo\API30\Ecommerce\Sale;
use Cielo\API30\Ecommerce\CieloEcommerce;
use Cielo\API30\Ecommerce\Payment;
use Cielo\API30\Ecommerce\CreditCard;
use Cielo\API30\Ecommerce\RecurrentPayment;

use Cielo\API30\Ecommerce\Request\CieloRequestException;

// Configure o ambiente em teste sandbox
//$environment = $environment = Environment::sandbox();

//$merchant = new Merchant('6dc6bd9c-4482-48b4-9c73-f559cc73e3af', 'BTZDUMLVXWEKDLUJKPTPLEGOVXRMRBMPFNETSDAF');

// Configure seu merchant Production
$environment = $environment = Environment::production();

$merchant = new Merchant('xxxxxxxxxxxxxxxxxxxx', 'yyyyyyyyyyyyyyyyyyyy');

// Crie uma instância de Sale informando o ID do pedido na loja
$sale = new Sale('123');

// Crie uma instância de Customer informando o nome do cliente
$customer = $sale->customer($_POST['nomeCartao']);

$_SESSION['valoroper'] = $_POST['total'];

// Crie uma instância de Payment informando o valor do pagamento
//$payment = $sale->payment((int) ($_POST['total'] . '00'));
//$payment = $sale->payment((float) ($_POST['total']));

$_SESSION['plandescription'] = $_POST['detalhePlano'];

//$_SESSION['startdate'] = $_POST['startDate'];

//$_SESSION['enddate'] = $_POST['endDate'];

//seções criadas para armazenar informações históricas
$_SESSION['startdate'] = date('Y-m-d', strtotime(str_replace('/', '-', $_POST['startDate'])));

$_SESSION['enddate'] = date('Y-m-d', strtotime(str_replace('/', '-', $_POST['endDate'])));

$_SESSION['mesano'] = $_POST['mensal-anual'];

// Configure a recorrência
$recurrent = new RecurrentPayment(true);

$recurrent = $recurrent->setInterval(RecurrentPayment::INTERVAL_MONTHLY)->setAuthorizeNow(true);

$recurrent = $recurrent->setStartDate(date('Y-m-d', strtotime(str_replace('/', '-', $_POST['startDate']))));
$recurrent = $recurrent->setEndDate(date('Y-m-d', strtotime(str_replace('/', '-', $_POST['endDate']))));
$recurrent = $recurrent->setInterval($_POST['mensal-anual']);

$payment = $sale->payment(str_replace('.','',$_POST['total']))
->setType("CreditCard")
->setCurrency("BRL")
->setCountry("BRA")
->setServiceTaxAmount(0)
->setInstallments(1)
->setCapture(false)
->setRecurrent(true)
->setSoftDescriptor("ListaFarma");

// Crie uma instância de Credit Card utilizando os dados de teste
$payment->setRecurrentPayment($recurrent)
->setType(Payment::PAYMENTTYPE_CREDITCARD)
->creditCard($_POST['codCVV'], $_POST['bandeiraCartao'])
->setExpirationDate($_POST['venctoCartao'])
->setCardNumber(str_replace('.', '', $_POST['numeroCartao']))
->setSaveCard(false)
->setHolder($_POST['nomeCartao']);

try {

// Configure o SDK com seu merchant e o ambiente apropriado para criar a venda
$sale = (new CieloEcommerce($merchant, $environment))->createSale($sale);

//var_dump(json_encode($sale));
//die();

// Com a venda criada na Cielo, já temos o ID do pagamento, TID e demais
// dados retornados pela Cielo

$recurrentPaymentId = $sale->getPayment()->getRecurrentPayment()->getRecurrentPaymentId();

$getNextRecurrency = $sale->getPayment()->getRecurrentPayment()->getNextRecurrency();

$paymentId = $sale->getPayment()->getPaymentId();

$typePayment = $sale->getPayment()->getType();

if($sale->getPayment()->getStatus() == 2){
//Header("Location: retorno.php?cod=0&TID=" . $sale->getPayment()->getTid());
$_SESSION['cod'] = "0";
$tid = $sale->getPayment()->getTid();
$_SESSION['tid'] = $tid;

Header("Location: /admin/farmacia/?pagina=planos");

}else{
$_SESSION['cod'] = "1";
$status = $sale->getPayment()->getStatus();
$_SESSION['status'] = $status;

//$coderro = $sale->getPayment()->getReturnCode();
//$_SESSION['coderro'] = $coderro;

//$erro = $sale->getPayment()->getReturnCode() . " - " . $sale->getPayment()->getReturnMessage();
$erro = $sale->getPayment()->getReturnCode();
//$erro = $sale->getPayment()->getReturnMessage();
$_SESSION['erro'] = $erro;

//Header("Location: retorno.php?cod=1&status=".$sale->getPayment()->getStatus()."&erro=".$sale->getPayment()->getReturnCode());
Header("Location: /admin/farmacia/?pagina=planos");
}

// Com o ID do pagamento, podemos fazer sua captura, se ela não tiver sido capturada ainda
//$sale = (new CieloEcommerce($merchant, $environment))->captureSale($paymentId, 15700, 0);

// E também podemos fazer seu cancelamento, se for o caso
//$sale = (new CieloEcommerce($merchant, $environment))->cancelSale($paymentId, 15700);
} catch (CieloRequestException $e) {

//var_dump($e);
//die();

$_SESSION['cod'] = "2";

//$erroe = $e->getCieloError()->getCode() . " - " . $e->getCieloError()->getMessage();

$erroe = $e->getCieloError()->getCode();
$_SESSION['erroe'] = $erroe;

//var_dump(json_encode($erroe));
//die();

// Em caso de erros de integração, podemos tratar o erro aqui.
// os códigos de erro estão todos disponíveis no manual de integração.
//print_r($e->getCieloError());
//$erro = $e->getCieloError()->getMessage() . "-" . $e->getCieloError()->getCode();
//echo $erro; die();
//echo $e->getCieloError()->code . $e->getCieloError()->message;
//Header("Location: retorno.php?cod=2&erro=" . $e->getCieloError()->getCode());

Header("Location: /admin/farmacia/?pagina=planos");

}

segue análise de log 
[Wed Feb 13 19:37:45.304282 2019] [:error] [pid 19496] [client 189.18.116.59:50419] PHP Fatal error:  Uncaught Error: Call to undefined function Cielo\\API30\\Ecommerce\\Request\\curl_init() in /var/www/html/admin/apicielo/vendor/developercielo/api-3.0-php/src/Cielo/API30/Ecommerce/Request/AbstractRequest.php:55\nStack trace:\n#0 /var/www/html/admin/apicielo/vendor/developercielo/api-3.0-php/src/Cielo/API30/Ecommerce/Request/CreateSaleRequest.php(43): Cielo\\API30\\Ecommerce\\Request\\AbstractRequest->sendRequest('POST', 'https://api.cie...', Object(Cielo\\API30\\Ecommerce\\Sale))\n#1 /var/www/html/admin/apicielo/vendor/developercielo/api-3.0-php/src/Cielo/API30/Ecommerce/CieloEcommerce.php(61): Cielo\\API30\\Ecommerce\\Request\\CreateSaleRequest->execute(Object(Cielo\\API30\\Ecommerce\\Sale))\n#2 **_/var/www/html/admin/apicielo/efetuar-pagamento.php(87): Cielo\\API30\\Ecommerce\\CieloEcommerce->createSale(Object(Cielo\\API30\\Ecommerce\\Sale))\n_**#3 {main}\n  thrown in /var/www/html/admin/apicielo/vendor/developercielo/api-3.0-php/src/Cielo/API30/Ecommerce/Request/AbstractRequest.php on line 55, referer: https://www.listafarma.com/admin/farmacia/?pagina=planos
ubuntu@ip-172-31-28-128:/var/log/apache2$

**Minha observação é que não está permitindo criar o >createSale(Object(Cielo\\API30\\Ecommerce\\Sale))**

Obrigado.

**Comment by JacksonBelizario** [comment]
Duplicate of #135
