### ISSUE TITLE
Erro Unknown SSL :443

### ISSUE THREAD

**Issue by paulortoledo** [DeveloperCielo/API-3.0-PHP#155]
Fiz o teste local e funcionou normal. Coloquei no servidor locaweb e gera esse erro.
Temos o certificado instalado. Os analistas da cielo informou que era um erro do servidor, os analistas da locaweb cada um dá uma versão.

Alguém consegue me ajudar?

Fatal error: Uncaught exception 'RuntimeException' with message 'Curl error: Unknown SSL protocol error in connection to apisandbox.cieloecommerce.cielo.com.br:443 ' in /home/storage/d/df/e5/institutomelocor1/public_html/imcteste/IntegraTS/apicielo/vendor/developercielo/api-3.0-php/src/Cielo/API30/Ecommerce/Request/AbstractRequest.php:85 Stack trace: #0 /home/storage/d/df/e5/institutomelocor1/public_html/imcteste/IntegraTS/apicielo/vendor/developercielo/api-3.0-php/src/Cielo/API30/Ecommerce/Request/CreateSaleRequest.php(43): Cielo\API30\Ecommerce\Request\AbstractRequest->sendRequest('POST', 'https://apisand...', Object(Cielo\API30\Ecommerce\Sale)) #1 /home/storage/d/df/e5/institutomelocor1/public_html/imcteste/IntegraTS/apicielo/vendor/developercielo/api-3.0-php/src/Cielo/API30/Ecommerce/CieloEcommerce.php(61): Cielo\API30\Ecommerce\Request\CreateSaleRequest->execute(Object(Cielo\API30\Ecommerce\Sale)) #2 /home/storage/d/df/e5/institutomelocor1/public_html/imcteste/IntegraTS/apicielo/apppagunico.php(135): Cielo\API30\Ecom in /home/storage/d/df/e5/institutomelocor1/public_html/imcteste/IntegraTS/apicielo/vendor/developercielo/api-3.0-php/src/Cielo/API30/Ecommerce/Request/AbstractRequest.php on line 85

**Comment by souzadavi** [comment]
Provavelmente o problema é na LOCAWEB. Teste em outro servidor, se tiver dificuldade em contratar outro servidor. Me avisa que consigo uma conta de teste para vc.
