### ISSUE TITLE
Função para desabilitar/reabilitar pagamentos recorrentes

### ISSUE THREAD

**Issue by marcelo2605** [DeveloperCielo/API-3.0-PHP#71]
Existe funções prontas para essas duas ações? Estou tentando usar
`
$sale = (new CieloEcommerce($merchant, $environment))->cancelSale($paymentId, 15700);`
mas retorna erro.

> Fatal error: Uncaught Cielo\API30\Ecommerce\Request\CieloRequestException: Request Error in /var/www/public/wp-content/themes/feal_clube/inc/vendor/developercielo/api-3.0-php/src/Cielo/API30/Ecommerce/Request/AbstractSaleRequest.php:85 Stack trace: #0 /var/www/public/wp-content/themes/feal_clube/inc/vendor/developercielo/api-3.0-php/src/Cielo/API30/Ecommerce/Request/AbstractSaleRequest.php(67): Cielo\API30\Ecommerce\Request\AbstractSaleRequest->readResponse(400, '[\r\n {\r\n "Co...') #1 /var/www/public/wp-content/themes/feal_clube/inc/vendor/developercielo/api-3.0-php/src/Cielo/API30/Ecommerce/Request/UpdateSaleRequest.php(43): Cielo\API30\Ecommerce\Request\AbstractSaleRequest->sendRequest('PUT', 'https://apisand...') #2 /var/www/public/wp-content/themes/feal_clube/inc/vendor/developercielo/api-3.0-php/src/Cielo/API30/Ecommerce/CieloEcommerce.php(116): Cielo\API30\Ecommerce\Request\UpdateSaleRequest->execute('19b9f748-5f93-4...') #3 /var/www/public/wp-content/themes/feal_clube/inc/cielo.php(598): Cielo\API30\Ecommerce in /var/www/public/wp-content/themes/feal_clube/inc/vendor/developercielo/api-3.0-php/src/Cielo/API30/Ecommerce/Request/AbstractSaleRequest.php on line 85

**Comment by marcelo2605** [comment]
Resolvido. Criei uma classe para cada um desses itens.
